
#Pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
nparr = np.arange(0,20)
nparr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
newarr = nparr.reshape(5,4)
newarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
df = pd.DataFrame(newarr,index=['row1','row2','row3','row4','row5'])
df

0   1   2   3
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [6]:
df = pd.DataFrame(newarr,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [13]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int64
 1   col2    5 non-null      int64
 2   col3    5 non-null      int64
 3   col4    5 non-null      int64
dtypes: int64(4)
memory usage: 360.0+ bytes


In [15]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [8]:
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int64

In [11]:
type(df)

pandas.core.frame.DataFrame

In [16]:
type(df.loc['row1'])

pandas.core.series.Series

In [17]:
df.iloc[:,:]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [18]:
df.iloc[:2,:]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

In [20]:
df.iloc[:2,:3]

col1  col2  col3
row1     0     1     2
row2     4     5     6

In [21]:
type(df.iloc[:,:])

pandas.core.frame.DataFrame

In [22]:
df.iloc[:,:1]

col1
row1     0
row2     4
row3     8
row4    12
row5    16

In [23]:
type(df.iloc[:,:1])

pandas.core.frame.DataFrame

#Convert DataFrames into array

In [24]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
df.iloc[:,:].values.shape

(5, 4)

In [26]:
df['col1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int64

In [27]:
df['col1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: col1, dtype: int64

In [28]:
df.isnull()

col1   col2   col3   col4
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False
row5  False  False  False  False

In [30]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [31]:
df['col1'].unique()

array([ 0,  4,  8, 12, 16])

In [32]:
df['col1','col2']

KeyError: ignored

In [33]:
df[['col1','col2']]

col1  col2
row1     0     1
row2     4     5
row3     8     9
row4    12    13
row5    16    17

In [34]:
type(df[['col1','col2']])

pandas.core.frame.DataFrame